### ISSUE TITLE
Cannot run test on Windows

### ISSUE THREAD

**Issue by hiepxanh** [syntax-tree/mdast-util-gfm-autolink-literal#13]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=issues) and [discussions](https://github.com/orgs/syntax-tree/discussions) and couldn’t find anything (or linked relevant results below)

### Affected package

2.0.1

### Steps to reproduce

- clone 
- npm install
- npm test

### Actual behavior

```
test at test\index.js:468:13
✖ should work on `www-path-start` (10.3949ms)
  AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
  + actual - expected ... Lines skipped

  + '<h1>wwwtf? (3)</h1>\n' +
  +   '<p><a href="http://www.a/">www.a/</a> (space)</p>\n' +
  +   '<p><a href="http://www.a/">www.a/</a>!</p>\n' +
  +   '<p><a href="http://www.a/">www.a/</a>"</p>\n' +
  +   '<p><a href="http://www.a/#">www.a/#</a></p>\n' +
  +   '<p><a href="http://www.a/$">www.a/$</a></p>\n' +
  +   '<p><a href="http://www.a/%25">www.a/%</a></p>\n' +
  +   '<p><a href="http://www.a/&amp;">www.a/&amp;</a></p>\n' +
  +   `<p><a href="http://www.a/">www.a/</a>'</p>\n` +
  +   '<p><a href="http://www.a/(">www.a/(</a></p>\n' +
  +   '<p><a href="http://www.a/">www.a/</a>)</p>\n' +
  +   '<p><a href="http://www.a/">www.a/</a>*</p>\n' +
  +   '<p><a href="http://www.a/+">www.a/+</a></p>\n' +
  +   '<p><a href="http://www.a/">www.a/</a>,</p>\n' +
  +   '<p><a href="http://www.a/-">www.a/-</a></p>\n' +
  +   '<p><a href="http://www.a/">www.a/</a></p>\n' +
  +   '<p><a href="http://www.a/">www.a/</a>.</p>\n' +
  +   '<p><a href="http://www.a//">www.a//</a></p>\n' +
  +   '<p><a href="http://www.a/">www.a/</a>:</p>\n' +
  +   '<p><a href="http://www.a/">www.a/</a>;</p>\n' +
  +   '<p><a href="http://www.a/">www.a/</a>&lt;</p>\n' +
  +   '<p><a href="http://www.a/=">www.a/=</a></p>\n' +
  +   '<p><a href="http://www.a/%3E">www.a/></a></p>\n' +
  +   '<p><a href="http://www.a/">www.a/</a>?</p>\n' +
  +   '<p><a href="http://www.a/@">www.a/@</a></p>\n' +
  +   '<p><a href="http://www.a/%5B">www.a/[</a></p>\n' +
  ...
  - '<h1>wwwtf? (3)</h1>\r\n' +
  -   '<p><a href="http://www.a/">www.a/</a> (space)</p>\r\n' +
  -   '<p><a href="http://www.a/">www.a/</a>!</p>\r\n' +
  -   '<p><a href="http://www.a/">www.a/</a>"</p>\r\n' +
  -   '<p><a href="http://www.a/#">www.a/#</a></p>\r\n' +
  -   '<p><a href="http://www.a/$">www.a/$</a></p>\r\n' +
  -   '<p><a href="http://www.a/%25">www.a/%</a></p>\r\n' +
  -   '<p><a href="http://www.a/&amp;">www.a/&amp;</a></p>\r\n' +
  -   `<p><a href="http://www.a/">www.a/</a>'</p>\r\n` +
  -   '<p><a href="http://www.a/(">www.a/(</a></p>\r\n' +
  -   '<p><a href="http://www.a/">www.a/</a>)</p>\r\n' +
  -   '<p><a href="http://www.a/">www.a/</a>*</p>\r\n' +
  -   '<p><a href="http://www.a/+">www.a/+</a></p>\r\n' +
  -   '<p><a href="http://www.a/">www.a/</a>,</p>\r\n' +
  -   '<p><a href="http://www.a/-">www.a/-</a></p>\r\n' +
  -   '<p><a href="http://www.a/">www.a/</a></p>\r\n' +
  -   '<p><a href="http://www.a/">www.a/</a>.</p>\r\n' +
  -   '<p><a href="http://www.a//">www.a//</a></p>\r\n' +
  -   '<p><a href="http://www.a/">www.a/</a>:</p>\r\n' +
  -   '<p><a href="http://www.a/">www.a/</a>;</p>\r\n' +
  -   '<p><a href="http://www.a/">www.a/</a>&lt;</p>\r\n' +
  -   '<p><a href="http://www.a/=">www.a/=</a></p>\r\n' +
  -   '<p><a href="http://www.a/%3E">www.a/></a></p>\r\n' +
  -   '<p><a href="http://www.a/">www.a/</a>?</p>\r\n' +
  -   '<p><a href="http://www.a/@">www.a/@</a></p>\r\n' +
  -   '<p><a href="http://www.a/%5B">www.a/[</a></p>\r\n' +
  ...
      at TestContext.<anonymous> (file:///C:/Users/hiepx/small-cosmos/mdast-util-gfm-autolink-literal/test/index.js:492:14)
      at async Test.run (node:internal/test_runner/test:935:9)
      at async TestContext.<anonymous> (file:///C:/Users/hiepx/small-cosmos/mdast-util-gfm-autolink-literal/test/index.js:468:5)
      at async Test.run (node:internal/test_runner/test:935:9)
      at async Test.processPendingSubtests (node:internal/test_runner/test:633:7) {
    generatedMessage: true,
    code: 'ERR_ASSERTION',
    actual: `<h1>wwwtf? (3)</h1>\n<p><a href="http://www.a/">www.a/</a> (space)</p>\n<p><a href="http://www.a/">www.a/</a>!</p>\n<p><a href="http://www.a/">www.a/</a>"</p>\n<p><a href="http://www.a/#">www.a/#</a></p>\n<p><a href="http://www.a/$">www.a/$</a></p>\n<p><a href="http://www.a/%25">www.a/%</a></p>\n<p><a href="http://www.a/&amp;">www.a/&amp;</a></p>\n<p><a href="http://www.a/">www.a/</a>'</p>\n<p><a href="http://www.a/(">www.a/(</a></p>\n...`,
    expected: `<h1>wwwtf? (3)</h1>\r\n<p><a href="http://www.a/">www.a/</a> (space)</p>\r\n<p><a href="http://www.a/">www.a/</a>!</p>\r\n<p><a href="http://www.a/">www.a/</a>"</p>\r\n<p><a href="http://www.a/#">www.a/#</a></p>\r\n<p><a href="http://www.a/$">www.a/$</a></p>\r\n<p><a href="http://www.a/%25">www.a/%</a></p>\r\n<p><a href="http://www.a/&amp;">www.a/&amp;</a></p>\r\n<p><a href="http://www.a/">www.a/</a>'</p>\r\n<p><a href="http://www.a/(">www.a/(</a></p>\r\n...`,
    operator: 'deepStrictEqual'
  }
  ```

### Expected behavior

it should not fail default test on fresh clone. I dont understand why, feeling it should work but guest that I'm working on windows and test build on linux, so must be some whitespace or weird character cause miss behavior on this.
I'm plan to make a PR as we discuss https://github.com/syntax-tree/mdast-util-gfm-autolink-literal/issues/10#issuecomment-2541252829 

### Runtime

v22.11.0

### Package manager

2.0.1

### Operating system

windows 11

### Build and bundle tools

other (please specify in steps to reproduce)

**Comment by wooorm** [comment]
Yes, this is because of windows line endings.
Which uses `\r\n` instead of `\n`.
PR welcome to handle those
